### ISSUE TITLE
bfx:hf:algo:ao-host failed to register AO UIs: 502 / 404

### ISSUE THREAD

**Issue by MC2k** [bitfinexcom/bfx-hf-algo-server#4]
Hello,
i try the server and it come to errors, when i use endpoint https://api-pub.bitfinex.com/v2/ i become the error  bfx:hf:algo:ao-host failed to register AO UIs: 502

When i try it with endpoint https://api.bitfinex.com/v2/ the error is bfx:hf:algo:ao-host failed to register AO UIs: 404 .

After this error the websocket register successful and in the bitifinex UI under "Orders" the status "HF Connected" appears but the trading strategys are not shown in the UI.

**Comment by lianopbs** [comment]
Check if the API you created has write permissions for orders

**Comment by f3rno** [comment]
@MC2k @lianopbs is correct
